// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjrncppafhueccsquefs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcm5jcHBhZmh1ZWNjc3F1ZWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDk5NTEsImV4cCI6MjA2MDYyNTk1MX0.4kXYYvQHVIdsgJsCriIwK5hh_aQaiEfewGkyRmLYYic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);